name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
      sudo apt-get install -y libx11-xcb-dev libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libpq-dev
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
