name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install xmllint
      run: sudo apt-get install libx11-xcb-dev libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
